### ISSUE TITLE
[bug] Tiredness Module configs of type long not available

### ISSUE THREAD

**Issue by grundyboy34** [CallMeFoxie/BetterSleeping2#3]
I've noticed that configs with type long within the tiredness module aren't available. (They don't get put into the config file, or read from it). This may be occurring for other modules as well, but I've only looked into the tiredness module as I wanted to change some minimum values.

**Comment by CallMeFoxie** [comment]
Selfnote: Needs to be fixed in
https://github.com/CallMeFoxie/FoxieLib/blob/master/src/main/java/foxie/lib/Config.java#L30

thanks for reporting!
