### ISSUE TITLE
[1.7.10-1.2.27] Server crash when a player logs in while server went offline while sleeping

### ISSUE THREAD

**Issue by Zethalion** [CallMeFoxie/BetterSleeping2#8]
Scenario:

Player is sleeping while the server is shutdown. After server reload and the player logs in, this crash occurs:
https://gist.github.com/Zethalion/eb99135d43c903051df681033263852f

I could fix it temporary by editing the player .dat file changing B:Sleeping=0 using nbteditor.

**Comment by CallMeFoxie** [comment]
I am afraid that 1.7.10 version is far from being maintained at this time anymore, it's just too old ;). Sorry!

**Comment by CallMeFoxie** [comment]
this seems to be related to potion effects when a player wakes up for whatever reason. Feel free to disable them completely.
